# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AlexTALL
email: alex.dubois@mac.com
description: > # this means to ignore newlines until "baseurl:"
  What it is to be a nerd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alextall.github.io" # the base hostname & protocol for your site
twitter_username: alextall
github_username:  alextall

paginate: 5

# Build settings
markdown: kramdown
kramdown:
  input: GFM
